/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var github_com_gogo_protobuf_gogoproto_gogo_pb = require('./github.com/gogo/protobuf/gogoproto/gogo_pb.js');
var google_protobuf_duration_pb = require('google-protobuf/google/protobuf/duration_pb.js');
var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
var uast_pb = require('./uast_pb.js');
goog.exportSymbol('proto.gopkg.in.bblfsh.sdk.v1.protocol.DriverManifest', null, global);
goog.exportSymbol('proto.gopkg.in.bblfsh.sdk.v1.protocol.Encoding', null, global);
goog.exportSymbol('proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseRequest', null, global);
goog.exportSymbol('proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseResponse', null, global);
goog.exportSymbol('proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseRequest', null, global);
goog.exportSymbol('proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseResponse', null, global);
goog.exportSymbol('proto.gopkg.in.bblfsh.sdk.v1.protocol.Status', null, global);
goog.exportSymbol('proto.gopkg.in.bblfsh.sdk.v1.protocol.SupportedLanguagesRequest', null, global);
goog.exportSymbol('proto.gopkg.in.bblfsh.sdk.v1.protocol.SupportedLanguagesResponse', null, global);
goog.exportSymbol('proto.gopkg.in.bblfsh.sdk.v1.protocol.VersionRequest', null, global);
goog.exportSymbol('proto.gopkg.in.bblfsh.sdk.v1.protocol.VersionResponse', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.DriverManifest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.gopkg.in.bblfsh.sdk.v1.protocol.DriverManifest.repeatedFields_, null);
};
goog.inherits(proto.gopkg.in.bblfsh.sdk.v1.protocol.DriverManifest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.gopkg.in.bblfsh.sdk.v1.protocol.DriverManifest.displayName = 'proto.gopkg.in.bblfsh.sdk.v1.protocol.DriverManifest';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.DriverManifest.repeatedFields_ = [5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.DriverManifest.prototype.toObject = function(opt_includeInstance) {
  return proto.gopkg.in.bblfsh.sdk.v1.protocol.DriverManifest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gopkg.in.bblfsh.sdk.v1.protocol.DriverManifest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.DriverManifest.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    language: jspb.Message.getFieldWithDefault(msg, 2, ""),
    version: jspb.Message.getFieldWithDefault(msg, 3, ""),
    status: jspb.Message.getFieldWithDefault(msg, 4, ""),
    featuresList: jspb.Message.getRepeatedField(msg, 5)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gopkg.in.bblfsh.sdk.v1.protocol.DriverManifest}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.DriverManifest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gopkg.in.bblfsh.sdk.v1.protocol.DriverManifest;
  return proto.gopkg.in.bblfsh.sdk.v1.protocol.DriverManifest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gopkg.in.bblfsh.sdk.v1.protocol.DriverManifest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gopkg.in.bblfsh.sdk.v1.protocol.DriverManifest}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.DriverManifest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setLanguage(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setVersion(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setStatus(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.addFeatures(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.DriverManifest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gopkg.in.bblfsh.sdk.v1.protocol.DriverManifest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gopkg.in.bblfsh.sdk.v1.protocol.DriverManifest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.DriverManifest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getLanguage();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getVersion();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getStatus();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getFeaturesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      5,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.DriverManifest.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.gopkg.in.bblfsh.sdk.v1.protocol.DriverManifest.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string language = 2;
 * @return {string}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.DriverManifest.prototype.getLanguage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.gopkg.in.bblfsh.sdk.v1.protocol.DriverManifest.prototype.setLanguage = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string version = 3;
 * @return {string}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.DriverManifest.prototype.getVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.gopkg.in.bblfsh.sdk.v1.protocol.DriverManifest.prototype.setVersion = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string status = 4;
 * @return {string}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.DriverManifest.prototype.getStatus = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.gopkg.in.bblfsh.sdk.v1.protocol.DriverManifest.prototype.setStatus = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * repeated string features = 5;
 * @return {!Array<string>}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.DriverManifest.prototype.getFeaturesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 5));
};


/** @param {!Array<string>} value */
proto.gopkg.in.bblfsh.sdk.v1.protocol.DriverManifest.prototype.setFeaturesList = function(value) {
  jspb.Message.setField(this, 5, value || []);
};


/**
 * @param {!string} value
 * @param {number=} opt_index
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.DriverManifest.prototype.addFeatures = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 5, value, opt_index);
};


proto.gopkg.in.bblfsh.sdk.v1.protocol.DriverManifest.prototype.clearFeaturesList = function() {
  this.setFeaturesList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseRequest.displayName = 'proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    filename: jspb.Message.getFieldWithDefault(msg, 1, ""),
    language: jspb.Message.getFieldWithDefault(msg, 2, ""),
    content: jspb.Message.getFieldWithDefault(msg, 3, ""),
    encoding: jspb.Message.getFieldWithDefault(msg, 4, 0),
    timeout: (f = msg.getTimeout()) && google_protobuf_duration_pb.Duration.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseRequest}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseRequest;
  return proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseRequest}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setFilename(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setLanguage(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setContent(value);
      break;
    case 4:
      var value = /** @type {!proto.gopkg.in.bblfsh.sdk.v1.protocol.Encoding} */ (reader.readEnum());
      msg.setEncoding(value);
      break;
    case 5:
      var value = new google_protobuf_duration_pb.Duration;
      reader.readMessage(value,google_protobuf_duration_pb.Duration.deserializeBinaryFromReader);
      msg.setTimeout(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFilename();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getLanguage();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getContent();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getEncoding();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
  f = message.getTimeout();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      google_protobuf_duration_pb.Duration.serializeBinaryToWriter
    );
  }
};


/**
 * optional string filename = 1;
 * @return {string}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseRequest.prototype.getFilename = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseRequest.prototype.setFilename = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string language = 2;
 * @return {string}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseRequest.prototype.getLanguage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseRequest.prototype.setLanguage = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string content = 3;
 * @return {string}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseRequest.prototype.getContent = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseRequest.prototype.setContent = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional Encoding encoding = 4;
 * @return {!proto.gopkg.in.bblfsh.sdk.v1.protocol.Encoding}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseRequest.prototype.getEncoding = function() {
  return /** @type {!proto.gopkg.in.bblfsh.sdk.v1.protocol.Encoding} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {!proto.gopkg.in.bblfsh.sdk.v1.protocol.Encoding} value */
proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseRequest.prototype.setEncoding = function(value) {
  jspb.Message.setProto3EnumField(this, 4, value);
};


/**
 * optional google.protobuf.Duration timeout = 5;
 * @return {?proto.google.protobuf.Duration}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseRequest.prototype.getTimeout = function() {
  return /** @type{?proto.google.protobuf.Duration} */ (
    jspb.Message.getWrapperField(this, google_protobuf_duration_pb.Duration, 5));
};


/** @param {?proto.google.protobuf.Duration|undefined} value */
proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseRequest.prototype.setTimeout = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseRequest.prototype.clearTimeout = function() {
  this.setTimeout(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseRequest.prototype.hasTimeout = function() {
  return jspb.Message.getField(this, 5) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseResponse.repeatedFields_, null);
};
goog.inherits(proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseResponse.displayName = 'proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseResponse';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseResponse.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    status: jspb.Message.getFieldWithDefault(msg, 1, 0),
    errorsList: jspb.Message.getRepeatedField(msg, 2),
    elapsed: (f = msg.getElapsed()) && google_protobuf_duration_pb.Duration.toObject(includeInstance, f),
    ast: jspb.Message.getFieldWithDefault(msg, 4, ""),
    language: jspb.Message.getFieldWithDefault(msg, 5, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseResponse}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseResponse;
  return proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseResponse}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.gopkg.in.bblfsh.sdk.v1.protocol.Status} */ (reader.readEnum());
      msg.setStatus(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.addErrors(value);
      break;
    case 3:
      var value = new google_protobuf_duration_pb.Duration;
      reader.readMessage(value,google_protobuf_duration_pb.Duration.deserializeBinaryFromReader);
      msg.setElapsed(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setAst(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setLanguage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getErrorsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f
    );
  }
  f = message.getElapsed();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_duration_pb.Duration.serializeBinaryToWriter
    );
  }
  f = message.getAst();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getLanguage();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * optional Status status = 1;
 * @return {!proto.gopkg.in.bblfsh.sdk.v1.protocol.Status}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseResponse.prototype.getStatus = function() {
  return /** @type {!proto.gopkg.in.bblfsh.sdk.v1.protocol.Status} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {!proto.gopkg.in.bblfsh.sdk.v1.protocol.Status} value */
proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseResponse.prototype.setStatus = function(value) {
  jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * repeated string errors = 2;
 * @return {!Array<string>}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseResponse.prototype.getErrorsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 2));
};


/** @param {!Array<string>} value */
proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseResponse.prototype.setErrorsList = function(value) {
  jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {!string} value
 * @param {number=} opt_index
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseResponse.prototype.addErrors = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseResponse.prototype.clearErrorsList = function() {
  this.setErrorsList([]);
};


/**
 * optional google.protobuf.Duration elapsed = 3;
 * @return {?proto.google.protobuf.Duration}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseResponse.prototype.getElapsed = function() {
  return /** @type{?proto.google.protobuf.Duration} */ (
    jspb.Message.getWrapperField(this, google_protobuf_duration_pb.Duration, 3));
};


/** @param {?proto.google.protobuf.Duration|undefined} value */
proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseResponse.prototype.setElapsed = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseResponse.prototype.clearElapsed = function() {
  this.setElapsed(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseResponse.prototype.hasElapsed = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string ast = 4;
 * @return {string}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseResponse.prototype.getAst = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseResponse.prototype.setAst = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string language = 5;
 * @return {string}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseResponse.prototype.getLanguage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.gopkg.in.bblfsh.sdk.v1.protocol.NativeParseResponse.prototype.setLanguage = function(value) {
  jspb.Message.setProto3StringField(this, 5, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseRequest.displayName = 'proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    filename: jspb.Message.getFieldWithDefault(msg, 1, ""),
    language: jspb.Message.getFieldWithDefault(msg, 2, ""),
    content: jspb.Message.getFieldWithDefault(msg, 3, ""),
    encoding: jspb.Message.getFieldWithDefault(msg, 4, 0),
    timeout: (f = msg.getTimeout()) && google_protobuf_duration_pb.Duration.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseRequest}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseRequest;
  return proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseRequest}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setFilename(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setLanguage(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setContent(value);
      break;
    case 4:
      var value = /** @type {!proto.gopkg.in.bblfsh.sdk.v1.protocol.Encoding} */ (reader.readEnum());
      msg.setEncoding(value);
      break;
    case 5:
      var value = new google_protobuf_duration_pb.Duration;
      reader.readMessage(value,google_protobuf_duration_pb.Duration.deserializeBinaryFromReader);
      msg.setTimeout(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFilename();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getLanguage();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getContent();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getEncoding();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
  f = message.getTimeout();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      google_protobuf_duration_pb.Duration.serializeBinaryToWriter
    );
  }
};


/**
 * optional string filename = 1;
 * @return {string}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseRequest.prototype.getFilename = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseRequest.prototype.setFilename = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string language = 2;
 * @return {string}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseRequest.prototype.getLanguage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseRequest.prototype.setLanguage = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string content = 3;
 * @return {string}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseRequest.prototype.getContent = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseRequest.prototype.setContent = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional Encoding encoding = 4;
 * @return {!proto.gopkg.in.bblfsh.sdk.v1.protocol.Encoding}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseRequest.prototype.getEncoding = function() {
  return /** @type {!proto.gopkg.in.bblfsh.sdk.v1.protocol.Encoding} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {!proto.gopkg.in.bblfsh.sdk.v1.protocol.Encoding} value */
proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseRequest.prototype.setEncoding = function(value) {
  jspb.Message.setProto3EnumField(this, 4, value);
};


/**
 * optional google.protobuf.Duration timeout = 5;
 * @return {?proto.google.protobuf.Duration}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseRequest.prototype.getTimeout = function() {
  return /** @type{?proto.google.protobuf.Duration} */ (
    jspb.Message.getWrapperField(this, google_protobuf_duration_pb.Duration, 5));
};


/** @param {?proto.google.protobuf.Duration|undefined} value */
proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseRequest.prototype.setTimeout = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseRequest.prototype.clearTimeout = function() {
  this.setTimeout(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseRequest.prototype.hasTimeout = function() {
  return jspb.Message.getField(this, 5) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseResponse.repeatedFields_, null);
};
goog.inherits(proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseResponse.displayName = 'proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseResponse';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseResponse.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    status: jspb.Message.getFieldWithDefault(msg, 1, 0),
    errorsList: jspb.Message.getRepeatedField(msg, 2),
    elapsed: (f = msg.getElapsed()) && google_protobuf_duration_pb.Duration.toObject(includeInstance, f),
    uast: (f = msg.getUast()) && uast_pb.Node.toObject(includeInstance, f),
    language: jspb.Message.getFieldWithDefault(msg, 5, ""),
    filename: jspb.Message.getFieldWithDefault(msg, 6, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseResponse}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseResponse;
  return proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseResponse}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.gopkg.in.bblfsh.sdk.v1.protocol.Status} */ (reader.readEnum());
      msg.setStatus(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.addErrors(value);
      break;
    case 3:
      var value = new google_protobuf_duration_pb.Duration;
      reader.readMessage(value,google_protobuf_duration_pb.Duration.deserializeBinaryFromReader);
      msg.setElapsed(value);
      break;
    case 4:
      var value = new uast_pb.Node;
      reader.readMessage(value,uast_pb.Node.deserializeBinaryFromReader);
      msg.setUast(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setLanguage(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setFilename(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getErrorsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f
    );
  }
  f = message.getElapsed();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_duration_pb.Duration.serializeBinaryToWriter
    );
  }
  f = message.getUast();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      uast_pb.Node.serializeBinaryToWriter
    );
  }
  f = message.getLanguage();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getFilename();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
};


/**
 * optional Status status = 1;
 * @return {!proto.gopkg.in.bblfsh.sdk.v1.protocol.Status}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseResponse.prototype.getStatus = function() {
  return /** @type {!proto.gopkg.in.bblfsh.sdk.v1.protocol.Status} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {!proto.gopkg.in.bblfsh.sdk.v1.protocol.Status} value */
proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseResponse.prototype.setStatus = function(value) {
  jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * repeated string errors = 2;
 * @return {!Array<string>}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseResponse.prototype.getErrorsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 2));
};


/** @param {!Array<string>} value */
proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseResponse.prototype.setErrorsList = function(value) {
  jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {!string} value
 * @param {number=} opt_index
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseResponse.prototype.addErrors = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseResponse.prototype.clearErrorsList = function() {
  this.setErrorsList([]);
};


/**
 * optional google.protobuf.Duration elapsed = 3;
 * @return {?proto.google.protobuf.Duration}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseResponse.prototype.getElapsed = function() {
  return /** @type{?proto.google.protobuf.Duration} */ (
    jspb.Message.getWrapperField(this, google_protobuf_duration_pb.Duration, 3));
};


/** @param {?proto.google.protobuf.Duration|undefined} value */
proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseResponse.prototype.setElapsed = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseResponse.prototype.clearElapsed = function() {
  this.setElapsed(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseResponse.prototype.hasElapsed = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional gopkg.in.bblfsh.sdk.v1.uast.Node uast = 4;
 * @return {?proto.gopkg.in.bblfsh.sdk.v1.uast.Node}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseResponse.prototype.getUast = function() {
  return /** @type{?proto.gopkg.in.bblfsh.sdk.v1.uast.Node} */ (
    jspb.Message.getWrapperField(this, uast_pb.Node, 4));
};


/** @param {?proto.gopkg.in.bblfsh.sdk.v1.uast.Node|undefined} value */
proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseResponse.prototype.setUast = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseResponse.prototype.clearUast = function() {
  this.setUast(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseResponse.prototype.hasUast = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional string language = 5;
 * @return {string}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseResponse.prototype.getLanguage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseResponse.prototype.setLanguage = function(value) {
  jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string filename = 6;
 * @return {string}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseResponse.prototype.getFilename = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.gopkg.in.bblfsh.sdk.v1.protocol.ParseResponse.prototype.setFilename = function(value) {
  jspb.Message.setProto3StringField(this, 6, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.SupportedLanguagesRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.gopkg.in.bblfsh.sdk.v1.protocol.SupportedLanguagesRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.gopkg.in.bblfsh.sdk.v1.protocol.SupportedLanguagesRequest.displayName = 'proto.gopkg.in.bblfsh.sdk.v1.protocol.SupportedLanguagesRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.SupportedLanguagesRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.gopkg.in.bblfsh.sdk.v1.protocol.SupportedLanguagesRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gopkg.in.bblfsh.sdk.v1.protocol.SupportedLanguagesRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.SupportedLanguagesRequest.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gopkg.in.bblfsh.sdk.v1.protocol.SupportedLanguagesRequest}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.SupportedLanguagesRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gopkg.in.bblfsh.sdk.v1.protocol.SupportedLanguagesRequest;
  return proto.gopkg.in.bblfsh.sdk.v1.protocol.SupportedLanguagesRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gopkg.in.bblfsh.sdk.v1.protocol.SupportedLanguagesRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gopkg.in.bblfsh.sdk.v1.protocol.SupportedLanguagesRequest}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.SupportedLanguagesRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.SupportedLanguagesRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gopkg.in.bblfsh.sdk.v1.protocol.SupportedLanguagesRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gopkg.in.bblfsh.sdk.v1.protocol.SupportedLanguagesRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.SupportedLanguagesRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.SupportedLanguagesResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.gopkg.in.bblfsh.sdk.v1.protocol.SupportedLanguagesResponse.repeatedFields_, null);
};
goog.inherits(proto.gopkg.in.bblfsh.sdk.v1.protocol.SupportedLanguagesResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.gopkg.in.bblfsh.sdk.v1.protocol.SupportedLanguagesResponse.displayName = 'proto.gopkg.in.bblfsh.sdk.v1.protocol.SupportedLanguagesResponse';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.SupportedLanguagesResponse.repeatedFields_ = [2,4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.SupportedLanguagesResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.gopkg.in.bblfsh.sdk.v1.protocol.SupportedLanguagesResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gopkg.in.bblfsh.sdk.v1.protocol.SupportedLanguagesResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.SupportedLanguagesResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    status: jspb.Message.getFieldWithDefault(msg, 1, 0),
    errorsList: jspb.Message.getRepeatedField(msg, 2),
    elapsed: (f = msg.getElapsed()) && google_protobuf_duration_pb.Duration.toObject(includeInstance, f),
    languagesList: jspb.Message.toObjectList(msg.getLanguagesList(),
    proto.gopkg.in.bblfsh.sdk.v1.protocol.DriverManifest.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gopkg.in.bblfsh.sdk.v1.protocol.SupportedLanguagesResponse}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.SupportedLanguagesResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gopkg.in.bblfsh.sdk.v1.protocol.SupportedLanguagesResponse;
  return proto.gopkg.in.bblfsh.sdk.v1.protocol.SupportedLanguagesResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gopkg.in.bblfsh.sdk.v1.protocol.SupportedLanguagesResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gopkg.in.bblfsh.sdk.v1.protocol.SupportedLanguagesResponse}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.SupportedLanguagesResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.gopkg.in.bblfsh.sdk.v1.protocol.Status} */ (reader.readEnum());
      msg.setStatus(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.addErrors(value);
      break;
    case 3:
      var value = new google_protobuf_duration_pb.Duration;
      reader.readMessage(value,google_protobuf_duration_pb.Duration.deserializeBinaryFromReader);
      msg.setElapsed(value);
      break;
    case 4:
      var value = new proto.gopkg.in.bblfsh.sdk.v1.protocol.DriverManifest;
      reader.readMessage(value,proto.gopkg.in.bblfsh.sdk.v1.protocol.DriverManifest.deserializeBinaryFromReader);
      msg.addLanguages(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.SupportedLanguagesResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gopkg.in.bblfsh.sdk.v1.protocol.SupportedLanguagesResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gopkg.in.bblfsh.sdk.v1.protocol.SupportedLanguagesResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.SupportedLanguagesResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getErrorsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f
    );
  }
  f = message.getElapsed();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_duration_pb.Duration.serializeBinaryToWriter
    );
  }
  f = message.getLanguagesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.gopkg.in.bblfsh.sdk.v1.protocol.DriverManifest.serializeBinaryToWriter
    );
  }
};


/**
 * optional Status status = 1;
 * @return {!proto.gopkg.in.bblfsh.sdk.v1.protocol.Status}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.SupportedLanguagesResponse.prototype.getStatus = function() {
  return /** @type {!proto.gopkg.in.bblfsh.sdk.v1.protocol.Status} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {!proto.gopkg.in.bblfsh.sdk.v1.protocol.Status} value */
proto.gopkg.in.bblfsh.sdk.v1.protocol.SupportedLanguagesResponse.prototype.setStatus = function(value) {
  jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * repeated string errors = 2;
 * @return {!Array<string>}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.SupportedLanguagesResponse.prototype.getErrorsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 2));
};


/** @param {!Array<string>} value */
proto.gopkg.in.bblfsh.sdk.v1.protocol.SupportedLanguagesResponse.prototype.setErrorsList = function(value) {
  jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {!string} value
 * @param {number=} opt_index
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.SupportedLanguagesResponse.prototype.addErrors = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


proto.gopkg.in.bblfsh.sdk.v1.protocol.SupportedLanguagesResponse.prototype.clearErrorsList = function() {
  this.setErrorsList([]);
};


/**
 * optional google.protobuf.Duration elapsed = 3;
 * @return {?proto.google.protobuf.Duration}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.SupportedLanguagesResponse.prototype.getElapsed = function() {
  return /** @type{?proto.google.protobuf.Duration} */ (
    jspb.Message.getWrapperField(this, google_protobuf_duration_pb.Duration, 3));
};


/** @param {?proto.google.protobuf.Duration|undefined} value */
proto.gopkg.in.bblfsh.sdk.v1.protocol.SupportedLanguagesResponse.prototype.setElapsed = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.gopkg.in.bblfsh.sdk.v1.protocol.SupportedLanguagesResponse.prototype.clearElapsed = function() {
  this.setElapsed(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.SupportedLanguagesResponse.prototype.hasElapsed = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * repeated DriverManifest languages = 4;
 * @return {!Array<!proto.gopkg.in.bblfsh.sdk.v1.protocol.DriverManifest>}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.SupportedLanguagesResponse.prototype.getLanguagesList = function() {
  return /** @type{!Array<!proto.gopkg.in.bblfsh.sdk.v1.protocol.DriverManifest>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.gopkg.in.bblfsh.sdk.v1.protocol.DriverManifest, 4));
};


/** @param {!Array<!proto.gopkg.in.bblfsh.sdk.v1.protocol.DriverManifest>} value */
proto.gopkg.in.bblfsh.sdk.v1.protocol.SupportedLanguagesResponse.prototype.setLanguagesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.gopkg.in.bblfsh.sdk.v1.protocol.DriverManifest=} opt_value
 * @param {number=} opt_index
 * @return {!proto.gopkg.in.bblfsh.sdk.v1.protocol.DriverManifest}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.SupportedLanguagesResponse.prototype.addLanguages = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.gopkg.in.bblfsh.sdk.v1.protocol.DriverManifest, opt_index);
};


proto.gopkg.in.bblfsh.sdk.v1.protocol.SupportedLanguagesResponse.prototype.clearLanguagesList = function() {
  this.setLanguagesList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.VersionRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.gopkg.in.bblfsh.sdk.v1.protocol.VersionRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.gopkg.in.bblfsh.sdk.v1.protocol.VersionRequest.displayName = 'proto.gopkg.in.bblfsh.sdk.v1.protocol.VersionRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.VersionRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.gopkg.in.bblfsh.sdk.v1.protocol.VersionRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gopkg.in.bblfsh.sdk.v1.protocol.VersionRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.VersionRequest.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gopkg.in.bblfsh.sdk.v1.protocol.VersionRequest}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.VersionRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gopkg.in.bblfsh.sdk.v1.protocol.VersionRequest;
  return proto.gopkg.in.bblfsh.sdk.v1.protocol.VersionRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gopkg.in.bblfsh.sdk.v1.protocol.VersionRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gopkg.in.bblfsh.sdk.v1.protocol.VersionRequest}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.VersionRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.VersionRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gopkg.in.bblfsh.sdk.v1.protocol.VersionRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gopkg.in.bblfsh.sdk.v1.protocol.VersionRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.VersionRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.VersionResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.gopkg.in.bblfsh.sdk.v1.protocol.VersionResponse.repeatedFields_, null);
};
goog.inherits(proto.gopkg.in.bblfsh.sdk.v1.protocol.VersionResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.gopkg.in.bblfsh.sdk.v1.protocol.VersionResponse.displayName = 'proto.gopkg.in.bblfsh.sdk.v1.protocol.VersionResponse';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.VersionResponse.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.VersionResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.gopkg.in.bblfsh.sdk.v1.protocol.VersionResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gopkg.in.bblfsh.sdk.v1.protocol.VersionResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.VersionResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    status: jspb.Message.getFieldWithDefault(msg, 1, 0),
    errorsList: jspb.Message.getRepeatedField(msg, 2),
    elapsed: (f = msg.getElapsed()) && google_protobuf_duration_pb.Duration.toObject(includeInstance, f),
    version: jspb.Message.getFieldWithDefault(msg, 4, ""),
    build: (f = msg.getBuild()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gopkg.in.bblfsh.sdk.v1.protocol.VersionResponse}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.VersionResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gopkg.in.bblfsh.sdk.v1.protocol.VersionResponse;
  return proto.gopkg.in.bblfsh.sdk.v1.protocol.VersionResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gopkg.in.bblfsh.sdk.v1.protocol.VersionResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gopkg.in.bblfsh.sdk.v1.protocol.VersionResponse}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.VersionResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.gopkg.in.bblfsh.sdk.v1.protocol.Status} */ (reader.readEnum());
      msg.setStatus(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.addErrors(value);
      break;
    case 3:
      var value = new google_protobuf_duration_pb.Duration;
      reader.readMessage(value,google_protobuf_duration_pb.Duration.deserializeBinaryFromReader);
      msg.setElapsed(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setVersion(value);
      break;
    case 5:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setBuild(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.VersionResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gopkg.in.bblfsh.sdk.v1.protocol.VersionResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gopkg.in.bblfsh.sdk.v1.protocol.VersionResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.VersionResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getErrorsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f
    );
  }
  f = message.getElapsed();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_duration_pb.Duration.serializeBinaryToWriter
    );
  }
  f = message.getVersion();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getBuild();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional Status status = 1;
 * @return {!proto.gopkg.in.bblfsh.sdk.v1.protocol.Status}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.VersionResponse.prototype.getStatus = function() {
  return /** @type {!proto.gopkg.in.bblfsh.sdk.v1.protocol.Status} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {!proto.gopkg.in.bblfsh.sdk.v1.protocol.Status} value */
proto.gopkg.in.bblfsh.sdk.v1.protocol.VersionResponse.prototype.setStatus = function(value) {
  jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * repeated string errors = 2;
 * @return {!Array<string>}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.VersionResponse.prototype.getErrorsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 2));
};


/** @param {!Array<string>} value */
proto.gopkg.in.bblfsh.sdk.v1.protocol.VersionResponse.prototype.setErrorsList = function(value) {
  jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {!string} value
 * @param {number=} opt_index
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.VersionResponse.prototype.addErrors = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


proto.gopkg.in.bblfsh.sdk.v1.protocol.VersionResponse.prototype.clearErrorsList = function() {
  this.setErrorsList([]);
};


/**
 * optional google.protobuf.Duration elapsed = 3;
 * @return {?proto.google.protobuf.Duration}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.VersionResponse.prototype.getElapsed = function() {
  return /** @type{?proto.google.protobuf.Duration} */ (
    jspb.Message.getWrapperField(this, google_protobuf_duration_pb.Duration, 3));
};


/** @param {?proto.google.protobuf.Duration|undefined} value */
proto.gopkg.in.bblfsh.sdk.v1.protocol.VersionResponse.prototype.setElapsed = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.gopkg.in.bblfsh.sdk.v1.protocol.VersionResponse.prototype.clearElapsed = function() {
  this.setElapsed(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.VersionResponse.prototype.hasElapsed = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string version = 4;
 * @return {string}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.VersionResponse.prototype.getVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.gopkg.in.bblfsh.sdk.v1.protocol.VersionResponse.prototype.setVersion = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional google.protobuf.Timestamp build = 5;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.VersionResponse.prototype.getBuild = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 5));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.gopkg.in.bblfsh.sdk.v1.protocol.VersionResponse.prototype.setBuild = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


proto.gopkg.in.bblfsh.sdk.v1.protocol.VersionResponse.prototype.clearBuild = function() {
  this.setBuild(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.VersionResponse.prototype.hasBuild = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * @enum {number}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.Encoding = {
  UTF8: 0,
  BASE64: 1
};

/**
 * @enum {number}
 */
proto.gopkg.in.bblfsh.sdk.v1.protocol.Status = {
  OK: 0,
  ERROR: 1,
  FATAL: 2
};

goog.object.extend(exports, proto.gopkg.in.bblfsh.sdk.v1.protocol);
