/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var github_com_gogo_protobuf_gogoproto_gogo_pb = require('./github.com/gogo/protobuf/gogoproto/gogo_pb.js');
goog.exportSymbol('proto.gopkg.in.bblfsh.sdk.v1.uast.Node', null, global);
goog.exportSymbol('proto.gopkg.in.bblfsh.sdk.v1.uast.Position', null, global);
goog.exportSymbol('proto.gopkg.in.bblfsh.sdk.v1.uast.Role', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gopkg.in.bblfsh.sdk.v1.uast.Node = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.gopkg.in.bblfsh.sdk.v1.uast.Node.repeatedFields_, null);
};
goog.inherits(proto.gopkg.in.bblfsh.sdk.v1.uast.Node, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.gopkg.in.bblfsh.sdk.v1.uast.Node.displayName = 'proto.gopkg.in.bblfsh.sdk.v1.uast.Node';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.gopkg.in.bblfsh.sdk.v1.uast.Node.repeatedFields_ = [3,7];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gopkg.in.bblfsh.sdk.v1.uast.Node.prototype.toObject = function(opt_includeInstance) {
  return proto.gopkg.in.bblfsh.sdk.v1.uast.Node.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gopkg.in.bblfsh.sdk.v1.uast.Node} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gopkg.in.bblfsh.sdk.v1.uast.Node.toObject = function(includeInstance, msg) {
  var f, obj = {
    internalType: jspb.Message.getFieldWithDefault(msg, 1, ""),
    propertiesMap: (f = msg.getPropertiesMap()) ? f.toObject(includeInstance, undefined) : [],
    childrenList: jspb.Message.toObjectList(msg.getChildrenList(),
    proto.gopkg.in.bblfsh.sdk.v1.uast.Node.toObject, includeInstance),
    token: jspb.Message.getFieldWithDefault(msg, 4, ""),
    startPosition: (f = msg.getStartPosition()) && proto.gopkg.in.bblfsh.sdk.v1.uast.Position.toObject(includeInstance, f),
    endPosition: (f = msg.getEndPosition()) && proto.gopkg.in.bblfsh.sdk.v1.uast.Position.toObject(includeInstance, f),
    rolesList: jspb.Message.getRepeatedField(msg, 7)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gopkg.in.bblfsh.sdk.v1.uast.Node}
 */
proto.gopkg.in.bblfsh.sdk.v1.uast.Node.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gopkg.in.bblfsh.sdk.v1.uast.Node;
  return proto.gopkg.in.bblfsh.sdk.v1.uast.Node.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gopkg.in.bblfsh.sdk.v1.uast.Node} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gopkg.in.bblfsh.sdk.v1.uast.Node}
 */
proto.gopkg.in.bblfsh.sdk.v1.uast.Node.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setInternalType(value);
      break;
    case 2:
      var value = msg.getPropertiesMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "");
         });
      break;
    case 3:
      var value = new proto.gopkg.in.bblfsh.sdk.v1.uast.Node;
      reader.readMessage(value,proto.gopkg.in.bblfsh.sdk.v1.uast.Node.deserializeBinaryFromReader);
      msg.addChildren(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setToken(value);
      break;
    case 5:
      var value = new proto.gopkg.in.bblfsh.sdk.v1.uast.Position;
      reader.readMessage(value,proto.gopkg.in.bblfsh.sdk.v1.uast.Position.deserializeBinaryFromReader);
      msg.setStartPosition(value);
      break;
    case 6:
      var value = new proto.gopkg.in.bblfsh.sdk.v1.uast.Position;
      reader.readMessage(value,proto.gopkg.in.bblfsh.sdk.v1.uast.Position.deserializeBinaryFromReader);
      msg.setEndPosition(value);
      break;
    case 7:
      var value = /** @type {!Array<!proto.gopkg.in.bblfsh.sdk.v1.uast.Role>} */ (reader.readPackedEnum());
      msg.setRolesList(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gopkg.in.bblfsh.sdk.v1.uast.Node.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gopkg.in.bblfsh.sdk.v1.uast.Node.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gopkg.in.bblfsh.sdk.v1.uast.Node} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gopkg.in.bblfsh.sdk.v1.uast.Node.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getInternalType();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPropertiesMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(2, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
  f = message.getChildrenList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.gopkg.in.bblfsh.sdk.v1.uast.Node.serializeBinaryToWriter
    );
  }
  f = message.getToken();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getStartPosition();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.gopkg.in.bblfsh.sdk.v1.uast.Position.serializeBinaryToWriter
    );
  }
  f = message.getEndPosition();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.gopkg.in.bblfsh.sdk.v1.uast.Position.serializeBinaryToWriter
    );
  }
  f = message.getRolesList();
  if (f.length > 0) {
    writer.writePackedEnum(
      7,
      f
    );
  }
};


/**
 * optional string internal_type = 1;
 * @return {string}
 */
proto.gopkg.in.bblfsh.sdk.v1.uast.Node.prototype.getInternalType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.gopkg.in.bblfsh.sdk.v1.uast.Node.prototype.setInternalType = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * map<string, string> properties = 2;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.gopkg.in.bblfsh.sdk.v1.uast.Node.prototype.getPropertiesMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 2, opt_noLazyCreate,
      null));
};


proto.gopkg.in.bblfsh.sdk.v1.uast.Node.prototype.clearPropertiesMap = function() {
  this.getPropertiesMap().clear();
};


/**
 * repeated Node children = 3;
 * @return {!Array<!proto.gopkg.in.bblfsh.sdk.v1.uast.Node>}
 */
proto.gopkg.in.bblfsh.sdk.v1.uast.Node.prototype.getChildrenList = function() {
  return /** @type{!Array<!proto.gopkg.in.bblfsh.sdk.v1.uast.Node>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.gopkg.in.bblfsh.sdk.v1.uast.Node, 3));
};


/** @param {!Array<!proto.gopkg.in.bblfsh.sdk.v1.uast.Node>} value */
proto.gopkg.in.bblfsh.sdk.v1.uast.Node.prototype.setChildrenList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.gopkg.in.bblfsh.sdk.v1.uast.Node=} opt_value
 * @param {number=} opt_index
 * @return {!proto.gopkg.in.bblfsh.sdk.v1.uast.Node}
 */
proto.gopkg.in.bblfsh.sdk.v1.uast.Node.prototype.addChildren = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.gopkg.in.bblfsh.sdk.v1.uast.Node, opt_index);
};


proto.gopkg.in.bblfsh.sdk.v1.uast.Node.prototype.clearChildrenList = function() {
  this.setChildrenList([]);
};


/**
 * optional string token = 4;
 * @return {string}
 */
proto.gopkg.in.bblfsh.sdk.v1.uast.Node.prototype.getToken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.gopkg.in.bblfsh.sdk.v1.uast.Node.prototype.setToken = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional Position start_position = 5;
 * @return {?proto.gopkg.in.bblfsh.sdk.v1.uast.Position}
 */
proto.gopkg.in.bblfsh.sdk.v1.uast.Node.prototype.getStartPosition = function() {
  return /** @type{?proto.gopkg.in.bblfsh.sdk.v1.uast.Position} */ (
    jspb.Message.getWrapperField(this, proto.gopkg.in.bblfsh.sdk.v1.uast.Position, 5));
};


/** @param {?proto.gopkg.in.bblfsh.sdk.v1.uast.Position|undefined} value */
proto.gopkg.in.bblfsh.sdk.v1.uast.Node.prototype.setStartPosition = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


proto.gopkg.in.bblfsh.sdk.v1.uast.Node.prototype.clearStartPosition = function() {
  this.setStartPosition(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.gopkg.in.bblfsh.sdk.v1.uast.Node.prototype.hasStartPosition = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional Position end_position = 6;
 * @return {?proto.gopkg.in.bblfsh.sdk.v1.uast.Position}
 */
proto.gopkg.in.bblfsh.sdk.v1.uast.Node.prototype.getEndPosition = function() {
  return /** @type{?proto.gopkg.in.bblfsh.sdk.v1.uast.Position} */ (
    jspb.Message.getWrapperField(this, proto.gopkg.in.bblfsh.sdk.v1.uast.Position, 6));
};


/** @param {?proto.gopkg.in.bblfsh.sdk.v1.uast.Position|undefined} value */
proto.gopkg.in.bblfsh.sdk.v1.uast.Node.prototype.setEndPosition = function(value) {
  jspb.Message.setWrapperField(this, 6, value);
};


proto.gopkg.in.bblfsh.sdk.v1.uast.Node.prototype.clearEndPosition = function() {
  this.setEndPosition(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.gopkg.in.bblfsh.sdk.v1.uast.Node.prototype.hasEndPosition = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * repeated Role roles = 7;
 * @return {!Array<!proto.gopkg.in.bblfsh.sdk.v1.uast.Role>}
 */
proto.gopkg.in.bblfsh.sdk.v1.uast.Node.prototype.getRolesList = function() {
  return /** @type {!Array<!proto.gopkg.in.bblfsh.sdk.v1.uast.Role>} */ (jspb.Message.getRepeatedField(this, 7));
};


/** @param {!Array<!proto.gopkg.in.bblfsh.sdk.v1.uast.Role>} value */
proto.gopkg.in.bblfsh.sdk.v1.uast.Node.prototype.setRolesList = function(value) {
  jspb.Message.setField(this, 7, value || []);
};


/**
 * @param {!proto.gopkg.in.bblfsh.sdk.v1.uast.Role} value
 * @param {number=} opt_index
 */
proto.gopkg.in.bblfsh.sdk.v1.uast.Node.prototype.addRoles = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 7, value, opt_index);
};


proto.gopkg.in.bblfsh.sdk.v1.uast.Node.prototype.clearRolesList = function() {
  this.setRolesList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gopkg.in.bblfsh.sdk.v1.uast.Position = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.gopkg.in.bblfsh.sdk.v1.uast.Position, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.gopkg.in.bblfsh.sdk.v1.uast.Position.displayName = 'proto.gopkg.in.bblfsh.sdk.v1.uast.Position';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gopkg.in.bblfsh.sdk.v1.uast.Position.prototype.toObject = function(opt_includeInstance) {
  return proto.gopkg.in.bblfsh.sdk.v1.uast.Position.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gopkg.in.bblfsh.sdk.v1.uast.Position} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gopkg.in.bblfsh.sdk.v1.uast.Position.toObject = function(includeInstance, msg) {
  var f, obj = {
    offset: jspb.Message.getFieldWithDefault(msg, 1, 0),
    line: jspb.Message.getFieldWithDefault(msg, 2, 0),
    col: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gopkg.in.bblfsh.sdk.v1.uast.Position}
 */
proto.gopkg.in.bblfsh.sdk.v1.uast.Position.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gopkg.in.bblfsh.sdk.v1.uast.Position;
  return proto.gopkg.in.bblfsh.sdk.v1.uast.Position.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gopkg.in.bblfsh.sdk.v1.uast.Position} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gopkg.in.bblfsh.sdk.v1.uast.Position}
 */
proto.gopkg.in.bblfsh.sdk.v1.uast.Position.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setOffset(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setLine(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setCol(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gopkg.in.bblfsh.sdk.v1.uast.Position.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gopkg.in.bblfsh.sdk.v1.uast.Position.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gopkg.in.bblfsh.sdk.v1.uast.Position} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gopkg.in.bblfsh.sdk.v1.uast.Position.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOffset();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getLine();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
  f = message.getCol();
  if (f !== 0) {
    writer.writeUint32(
      3,
      f
    );
  }
};


/**
 * optional uint32 offset = 1;
 * @return {number}
 */
proto.gopkg.in.bblfsh.sdk.v1.uast.Position.prototype.getOffset = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.gopkg.in.bblfsh.sdk.v1.uast.Position.prototype.setOffset = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional uint32 line = 2;
 * @return {number}
 */
proto.gopkg.in.bblfsh.sdk.v1.uast.Position.prototype.getLine = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.gopkg.in.bblfsh.sdk.v1.uast.Position.prototype.setLine = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional uint32 col = 3;
 * @return {number}
 */
proto.gopkg.in.bblfsh.sdk.v1.uast.Position.prototype.getCol = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.gopkg.in.bblfsh.sdk.v1.uast.Position.prototype.setCol = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * @enum {number}
 */
proto.gopkg.in.bblfsh.sdk.v1.uast.Role = {
  INVALID: 0,
  IDENTIFIER: 1,
  QUALIFIED: 2,
  OPERATOR: 3,
  BINARY: 4,
  UNARY: 5,
  LEFT: 6,
  RIGHT: 7,
  INFIX: 8,
  POSTFIX: 9,
  BITWISE: 10,
  BOOLEAN: 11,
  UNSIGNED: 12,
  LEFT_SHIFT: 13,
  RIGHT_SHIFT: 14,
  OR: 15,
  XOR: 16,
  AND: 17,
  EXPRESSION: 18,
  STATEMENT: 19,
  EQUAL: 20,
  NOT: 21,
  LESS_THAN: 22,
  LESS_THAN_OR_EQUAL: 23,
  GREATER_THAN: 24,
  GREATER_THAN_OR_EQUAL: 25,
  IDENTICAL: 26,
  CONTAINS: 27,
  INCREMENT: 28,
  DECREMENT: 29,
  NEGATIVE: 30,
  POSITIVE: 31,
  DEREFERENCE: 32,
  TAKE_ADDRESS: 33,
  FILE: 34,
  ADD: 35,
  SUBSTRACT: 36,
  MULTIPLY: 37,
  DIVIDE: 38,
  MODULO: 39,
  PACKAGE: 40,
  DECLARATION: 41,
  IMPORT: 42,
  PATHNAME: 43,
  ALIAS: 44,
  FUNCTION: 45,
  BODY: 46,
  NAME: 47,
  RECEIVER: 48,
  ARGUMENT: 49,
  VALUE: 50,
  ARGS_LIST: 51,
  BASE: 52,
  IMPLEMENTS: 53,
  INSTANCE: 54,
  SUBTYPE: 55,
  SUBPACKAGE: 56,
  MODULE: 57,
  FRIEND: 58,
  WORLD: 59,
  IF: 60,
  CONDITION: 61,
  THEN: 62,
  ELSE: 63,
  SWITCH: 64,
  CASE: 65,
  DEFAULT: 66,
  FOR: 67,
  INITIALIZATION: 68,
  UPDATE: 69,
  ITERATOR: 70,
  WHILE: 71,
  DO_WHILE: 72,
  BREAK: 73,
  CONTINUE: 74,
  GOTO: 75,
  BLOCK: 76,
  SCOPE: 77,
  RETURN: 78,
  TRY: 79,
  CATCH: 80,
  FINALLY: 81,
  THROW: 82,
  ASSERT: 83,
  CALL: 84,
  CALLEE: 85,
  POSITIONAL: 86,
  NOOP: 87,
  LITERAL: 88,
  BYTE: 89,
  BYTE_STRING: 90,
  CHARACTER: 91,
  LIST: 92,
  MAP: 93,
  NULL: 94,
  NUMBER: 95,
  REGEXP: 96,
  SET: 97,
  STRING: 98,
  TUPLE: 99,
  TYPE: 100,
  ENTRY: 101,
  KEY: 102,
  PRIMITIVE: 103,
  ASSIGNMENT: 104,
  THIS: 105,
  COMMENT: 106,
  DOCUMENTATION: 107,
  WHITESPACE: 108,
  INCOMPLETE: 109,
  UNANNOTATED: 110,
  VISIBILITY: 111,
  ANNOTATION: 112,
  ANONYMOUS: 113,
  ENUMERATION: 114,
  ARITHMETIC: 115,
  RELATIONAL: 116,
  VARIABLE: 117
};

goog.object.extend(exports, proto.gopkg.in.bblfsh.sdk.v1.uast);
